// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDTLH30_s16afzfVzjbo9La2BaZxhuXKI',
    appId: '1:1041511516224:web:9c3a19139ada6271f777a5',
    messagingSenderId: '1041511516224',
    projectId: 'smart-chords',
    authDomain: 'smart-chords.firebaseapp.com',
    storageBucket: 'smart-chords.appspot.com',
    measurementId: 'G-RJ81ZSTF3Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXzYqJ8fiqOIBG_SmujYTESbEomF5Nqz8',
    appId: '1:1041511516224:android:ea3c776c992079bdf777a5',
    messagingSenderId: '1041511516224',
    projectId: 'smart-chords',
    storageBucket: 'smart-chords.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWB7hMA4WZchzEDo6uaazRDGm2GCirlyw',
    appId: '1:1041511516224:ios:0e92cec8f757925df777a5',
    messagingSenderId: '1041511516224',
    projectId: 'smart-chords',
    storageBucket: 'smart-chords.appspot.com',
    iosClientId:
        '1041511516224-ascqrhigli01ct9cvcpprd2mlokp14lg.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartChords',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWB7hMA4WZchzEDo6uaazRDGm2GCirlyw',
    appId: '1:1041511516224:ios:0e92cec8f757925df777a5',
    messagingSenderId: '1041511516224',
    projectId: 'smart-chords',
    storageBucket: 'smart-chords.appspot.com',
    iosClientId:
        '1041511516224-ascqrhigli01ct9cvcpprd2mlokp14lg.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartChords',
  );
}
